In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../Data/happiness.csv')
df[:3]

        Entity Code  Year  Cantril ladder score
0  Afghanistan  AFG  2011                 4.258
1  Afghanistan  AFG  2012                 4.040
2  Afghanistan  AFG  2014                 3.575

In [3]:
df_rename = df.copy()
df_rename.columns = ['Country', 'Code', 'Year', 'Happiness Score']
df_rename[:3]

       Country Code  Year  Happiness Score
0  Afghanistan  AFG  2011            4.258
1  Afghanistan  AFG  2012            4.040
2  Afghanistan  AFG  2014            3.575

In [4]:
df_rename.Year.unique()

array([2011, 2012, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022,
       2023, 2024])

In [5]:
df_rename.to_csv('../Data/happiness_clean.csv', index=False)