In [4]:
import pandas as pd

In [5]:
hdi = pd.read_csv('../Data/hdi_from2000_cleaned.csv')
happy = pd.read_csv('../Data/happiness_clean.csv')
hale = pd.read_csv('../Data/HALE_clean.csv')
co2 = pd.read_csv('../Data/co2_pc_clean.csv')
footprint = pd.read_csv('../Data/footprint_clean_2019.csv')
le = pd.read_csv('../Data/life_expectancy_clean.csv')
sdg = pd.read_csv('../Data/SDG_from2000_clean.csv')

In [6]:
# hdi[:3]
# happy[:3]
# hale[:3]
co2[:3]
# footprint[:3]
# sdg[:3]
# le[:3]

       Country  Year  annual CO2 emission pc. (in tonnes)
0  Afghanistan  1949                             0.001992
1  Afghanistan  1950                             0.010837
2  Afghanistan  1951                             0.011625

In [7]:
hale.Year.unique()

array([2000, 2010, 2015, 2019])

In [8]:
hale[(hale.Year == 2019) & (hale.Country == 'Somalia')]

     Country  Year  HALE (at birth)  HALE (at 60)
603  Somalia  2019             49.7          11.2

In [9]:
happy.columns = ['country', 'code', 'year', 'happiness score']
happy[:3]

       country code  year  happiness score
0  Afghanistan  AFG  2011            4.258
1  Afghanistan  AFG  2012            4.040
2  Afghanistan  AFG  2014            3.575

In [10]:
co2.columns = ['country', 'year', 'annual CO2 emission pc. (in tonnes)']
co2_2011 = co2[co2.year >= 2011]
co2_2011[:3]

        country  year  annual CO2 emission pc. (in tonnes)
62  Afghanistan  2011                             0.403382
63  Afghanistan  2012                             0.328381
64  Afghanistan  2013                             0.291832

In [11]:
happy_co2 = happy.merge(co2_2011, on=['country', 'year'], how='outer')
happy_co2[:5]

,country,code,year,happiness score,annual CO2 emission pc. (in tonnes)
0,Afghanistan,AFG,2011,4.258,0.403382
1,Afghanistan,AFG,2012,4.040,0.328381
2,Afghanistan,NaN,2013,NaN,0.291832
3,Afghanistan,AFG,2014,3.575,0.277077
4,Afghanistan,AFG,2015,3.360,0.285832

In [12]:
hdi_2011 = hdi[hdi.year >= 2011]
hdi_2011[:3]

     iso3      country hdicode region  hdi_rank_2022  year    hdi  pop_total
2266  AFG  Afghanistan     Low     SA          182.0  2011  0.457  29.249157
2267  ALB      Albania    High    ECA           74.0  2011  0.779   2.900654
2268  DZA      Algeria    High     AS           93.0  2011  0.725  36.543542

In [13]:
happy_co2_hdi = happy_co2.merge(hdi_2011, on=['country', 'year'], how='outer')
happy_co2_hdi[:4]

,country,code,year,happiness score,annual CO2 emission pc. (in tonnes),iso3,hdicode,region,hdi_rank_2022,hdi,pop_total
0,Afghanistan,AFG,2011,4.258,0.403382,AFG,Low,SA,182.0,0.457,29.249157
1,Afghanistan,AFG,2012,4.040,0.328381,AFG,Low,SA,182.0,0.467,30.466479
2,Afghanistan,NaN,2013,NaN,0.291832,AFG,Low,SA,182.0,0.475,31.541208
3,Afghanistan,AFG,2014,3.575,0.277077,AFG,Low,SA,182.0,0.480,32.716210

In [15]:
sdg_2011 = sdg[sdg.year >=2011]
sdg_2011.year.unique()

array([2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
       2022])

In [16]:
happy_co2_hdi_sdg = happy_co2_hdi.merge(sdg_2011, on=['country', 'year'], how='outer')
happy_co2_hdi_sdg[300:305]

,country,code,year,happiness score,annual CO2 emission pc. (in tonnes),iso3,hdicode,region,hdi_rank_2022,hdi,pop_total,iso,sdg_index
300,Belarus,BLR,2015,5.8020,6.197687,BLR,Very High,ECA,69.0,0.809,9.700609,NaN,NaN
301,Belarus,BLR,2016,5.5690,6.120052,BLR,Very High,ECA,69.0,0.809,9.708110,NaN,NaN
302,Belarus,BLR,2017,5.4830,6.253528,BLR,Very High,ECA,69.0,0.811,9.707876,NaN,NaN
303,Belarus,BLR,2018,5.3230,6.556654,BLR,Very High,ECA,69.0,0.812,9.695574,NaN,NaN
304,Belarus,BLR,2019,5.5399,6.581234,BLR,Very High,ECA,69.0,0.810,9.673971,NaN,NaN

In [17]:
#  consolidate iso/country columns
happy_co2_hdi_sdg['country_code'] = (
    happy_co2_hdi_sdg['code']
    .combine_first(happy_co2_hdi_sdg['iso'])
    .combine_first(happy_co2_hdi_sdg['iso3'])
)

happy_co2_hdi_sdg[200:205]

,country,code,year,happiness score,annual CO2 emission pc. (in tonnes),iso3,hdicode,region,hdi_rank_2022,hdi,pop_total,iso,sdg_index,country_code
200,Australia,AUS,2011,7.345,17.965439,AUS,Very High,NaN,10.0,0.927,22.357034,AUS,0.207,AUS
201,Australia,AUS,2012,7.350,17.774640,AUS,Very High,NaN,10.0,0.931,22.729269,AUS,0.206,AUS
202,Australia,NaN,2013,NaN,17.174370,AUS,Very High,NaN,10.0,0.929,23.111781,AUS,0.216,AUS
203,Australia,AUS,2014,7.284,16.644192,AUS,Very High,NaN,10.0,0.931,23.469579,AUS,0.214,AUS
204,Australia,AUS,2015,7.313,16.765380,AUS,Very High,NaN,10.0,0.933,23.820237,AUS,0.216,AUS

In [18]:
happy_co2_hdi_sdg_redux = happy_co2_hdi_sdg.drop(
    columns=['code', 'iso', 'iso3', 'hdi_rank_2022']
)
happy_co2_hdi_sdg_redux[400:403]

,country,year,happiness score,annual CO2 emission pc. (in tonnes),hdicode,region,hdi,pop_total,sdg_index,country_code
400,Bolivia (Plurinational State of),2020,NaN,NaN,Medium,LAC,0.691,11.936162,NaN,BOL
401,Bolivia (Plurinational State of),2021,NaN,NaN,Medium,LAC,0.691,12.079472,NaN,BOL
402,Bolivia (Plurinational State of),2022,NaN,NaN,Medium,LAC,0.698,12.224110,NaN,BOL

In [19]:
# creating bool series True for NaN values
hchsr = happy_co2_hdi_sdg_redux.copy()
null_series = pd.isnull(hchsr['happiness score'])
hchsr[null_series][:5]

,country,year,happiness score,annual CO2 emission pc. (in tonnes),hdicode,region,hdi,pop_total,sdg_index,country_code
0,*Kerala (India),2011,NaN,NaN,NaN,NaN,NaN,NaN,0.769,KRL
1,*Kerala (India),2012,NaN,NaN,NaN,NaN,NaN,NaN,0.776,KRL
2,*Kerala (India),2013,NaN,NaN,NaN,NaN,NaN,NaN,0.785,KRL
3,*Kerala (India),2014,NaN,NaN,NaN,NaN,NaN,NaN,0.795,KRL
4,*Kerala (India),2015,NaN,NaN,NaN,NaN,NaN,NaN,0.801,KRL

In [20]:
hchsr.isnull().sum()

country                                   0
year                                      0
happiness score                        1544
annual CO2 emission pc. (in tonnes)     653
hdicode                                1340
region                                 1844
hdi                                    1219
pop_total                              1184
sdg_index                              1700
country_code                            590
dtype: int64

In [ ]:
hchsr_nonnull = hchsr.dropna(subset=['happiness score'])
hchsr_nonnull.isnull().sum()

country                                   0
year                                      0
happiness score                           0
annual CO2 emission pc. (in tonnes)     173
hdicode                                 633
region                                 1040
hdi                                     626
pop_total                               622
sdg_index                               655
country_code                            130
dtype: int64

In [24]:
hchsr_nonnull_redux = hchsr_nonnull[
    [
        'country',
        'country_code',
        'year',
        'happiness score',
        'hdi',
        'sdg_index',
        'annual CO2 emission pc. (in tonnes)',
        'pop_total',
    ]
]
hchsr_nonnull_redux

,country,country_code,year,happiness score,hdi,sdg_index,annual CO2 emission pc. (in tonnes),pop_total
12,Afghanistan,AFG,2011,4.258,0.457,0.492,0.403382,29.249157
13,Afghanistan,AFG,2012,4.040,0.467,0.502,0.328381,30.466479
15,Afghanistan,AFG,2014,3.575,0.480,0.517,0.277077,32.716210
16,Afghanistan,AFG,2015,3.360,0.479,0.516,0.285832,33.753499
17,Afghanistan,AFG,2016,3.794,0.483,0.520,0.256664,34.636207
...,...,...,...,...,...,...,...,...
3651,Zimbabwe,ZWE,2020,3.145,0.554,0.596,0.547085,15.669666
3652,Zimbabwe,ZWE,2021,2.995,0.549,0.591,0.645915,15.993524
3653,Zimbabwe,ZWE,2022,3.204,0.550,0.593,0.648761,16.320537
3654,Zimbabwe,ZWE,2023,3.341,NaN,NaN,0.683201,NaN
3655,Zimbabwe,ZWE,2024,3.396,NaN,NaN,NaN,NaN

In [25]:
hchsr_nonnull_redux.to_csv('../Data/happy_sdg_hdi_co2_clean.csv', index=False)