In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('../Data/Life Expectancy.csv')
df[:3]

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2021,...,NaN,NaN,47.80,NaN,49.70,48.7 [47.8-49.7],NaN,NaN,EN,2024-08-01T22:00:00.000Z
1,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2021,...,NaN,NaN,48.45,NaN,50.92,49.6 [48.5-50.9],NaN,NaN,EN,2024-08-01T22:00:00.000Z
2,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2021,...,NaN,NaN,50.49,NaN,52.57,51.5 [50.5-52.6],NaN,NaN,EN,2024-08-01T22:00:00.000Z

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24420 entries, 0 to 24419
Data columns (total 34 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   IndicatorCode               24420 non-null  object
 1   Indicator                   24420 non-null  object
 2   ValueType                   24420 non-null  object
 3   ParentLocationCode          24420 non-null  object
 4   ParentLocation              24420 non-null  object
 5   Location type               24420 non-null  object
 6   SpatialDimValueCode         24420 non-null  object
 7   Location                    24420 non-null  object
 8   Period type                 24420 non-null  object
 9   Period                      24420 non-null  int64
 10  IsLatestYear                24420 non-null  bool
 11  Dim1 type                   24420 non-null  object
 12  Dim1                        24420 non-null  object
 13  Dim1ValueCode               24420 non-null  object
 14  Dim2 type                   0 non-null      float64
 15  Dim2                        0 non-null      float64
 16  Dim2ValueCode               0 non-null      float64
 17  Dim3 type                   0 non-null      float64
 18  Dim3                        0 non-null      float64
 19  Dim3ValueCode               0 non-null      float64
 20  DataSourceDimValueCode      0 non-null      float64
 21  DataSource                  0 non-null      float64
 22  FactValueNumericPrefix      0 non-null      float64
 23  FactValueNumeric            24420 non-null  float64
 24  FactValueUoM                0 non-null      float64
 25  FactValueNumericLowPrefix   0 non-null      float64
 26  FactValueNumericLow         24380 non-null  float64
 27  FactValueNumericHighPrefix  0 non-null      float64
 28  FactValueNumericHigh        24380 non-null  float64
 29  Value                       24420 non-null  object
 30  FactValueTranslationID      0 non-null      float64
 31  FactComments                0 non-null      float64
 32  Language                    24420 non-null  object
 33  DateModified                24420 non-null  object
dtypes: bool(1), float64(17), int64(1), object(15)
memory usage: 6.2+ MB

In [15]:
df_select = df[['ParentLocationCode', 'ParentLocation', 'Location', 'Period', 'Value']]
df_select[:4]

,ParentLocationCode,ParentLocation,Location,Period,Value
0,AFR,Africa,Lesotho,2021,48.7 [47.8-49.7]
1,AFR,Africa,Central African Republic,2021,49.6 [48.5-50.9]
2,AFR,Africa,Lesotho,2021,51.5 [50.5-52.6]
3,AFR,Africa,Eswatini,2021,51.6 [50.7-52.8]

In [21]:
df_order = df_select[
    ['Location', 'ParentLocation', 'ParentLocationCode', 'Period', 'Value']
]
df_order.columns = ['Country', 'Region', 'Country Code', 'Year', 'Life_Expectancy']
df_order[:4]

                    Country  Region Country Code  Year   Life_Expectancy
0                   Lesotho  Africa          AFR  2021  48.7 [47.8-49.7]
1  Central African Republic  Africa          AFR  2021  49.6 [48.5-50.9]
2                   Lesotho  Africa          AFR  2021  51.5 [50.5-52.6]
3                  Eswatini  Africa          AFR  2021  51.6 [50.7-52.8]

In [23]:
df_order[['Life_Expectancy Number', 'Life_Expectancy Range']] = (
    df_order['Life_Expectancy']
    .str.extract(r'^(\d+\.\d+)\s*\[([\d\.]+-[\d\.]+)\]')
    .copy()
)

df_order[:3]

/tmp/ipykernel_25609/3249397765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order[[

,Country,Region,Country Code,Year,Life_Expectancy,Life_Expectancy Number,Life_Expectancy Range
0,Lesotho,Africa,AFR,2021,48.7 [47.8-49.7],48.7,47.8-49.7
1,Central African Republic,Africa,AFR,2021,49.6 [48.5-50.9],49.6,48.5-50.9
2,Lesotho,Africa,AFR,2021,51.5 [50.5-52.6],51.5,50.5-52.6

In [24]:
df_order.drop(columns=['Life_Expectancy'], inplace=True)

/tmp/ipykernel_25609/3891071527.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_order.drop(columns=['Life_Expectancy'], inplace=True)

In [26]:
df_order[:3]
df_order.to_csv('../Data/life_expectancy_clean.csv', index=False)

In [2]:
df = pd.read_csv('../Data/life_expectancy_clean.csv')
df[:3]

,Country,Region,Country Code,Year,Life_Expectancy Number,Life_Expectancy Range
0,Lesotho,Africa,AFR,2021,48.7,47.8-49.7
1,Central African Republic,Africa,AFR,2021,49.6,48.5-50.9
2,Lesotho,Africa,AFR,2021,51.5,50.5-52.6

In [3]:
df.Year.unique()

array([2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011,
       2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000])