In [2]:
import pandas as pd

In [ ]:
data = pd.read_stata('../data/World_Values_Survey/Trends_VS_1981_2022_stata_v4_0.dta', convert_categoricals=False)
data[:2]

,studyno,version,doi,stdyno_w,versn_w,S001,s002,S002VS,S003,COUNTRY_ALPHA,...,Y022B,Y022C,Y023,Y023A,Y023B,Y023C,Y024,Y024A,Y024B,Y024C
0,4001,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,341,WVS3 v.20180912,2,3,3,8,ALB,...,0.66,1.0,0.296296,0.000000,0.444444,0.444444,0.165,0.33,0.0,0.165
1,4001,4-0-0 (2024-06-30),doi.org/10.14281/18241.27,341,WVS3 v.20180912,2,3,3,8,ALB,...,0.00,1.0,0.333333,0.111111,0.444444,0.444444,0.165,0.33,0.0,0.165

In [11]:
data.to_csv("wvs.csv")

In [22]:
path = "../data/World_Values_Survey/wvs_labels.CSV"

In [23]:
with open(path, "rb") as f:
    text = f.read()

In [24]:
text

b'ID ,"Common Dictionary: Variable name\n\n[Orange cells= variables included in JOINT EVS/WVS\n","Common Dictionary: Variable label\n"\r\n1,studyno,Study number\r\n2,version,Version\r\n3,doi,Digital Object Identifier \r\n4,stdyno_w,Study number (wave)\r\n5,studyno,Study number\r\n6,S001,Study\r\n7,S002,Wave\r\n8,S002evs,EVS-wave\r\n9,s002vs,Chronology of EVS-WVS waves\r\n10,S003,Country (ISO 3166-1 Numeric code)\r\n11,COW_ALPHA,CoW country code alpha\r\n12,COW_NUM,Country (CoW Numeric code)\r\n13,S004,Set\r\n14,S006,Original respondent number\r\n15,S007,Unified respondent number\r\n16,S007_01,Unified respondent number (EVS/WVS)\r\n17,S008,Interviewer number\r\n18,S009,Country (ISO 3166-1 Alpha-2 code)\r\n19,mode,Mode of data collection\r\n20,S010,Total length of interview\r\n21,S011A,Time of the interview - Start [hh.mm]\r\n22,S011B,Time of the interview - End [hh.mm]\r\n23,S012,Date interview [YYYYMMDD]\r\n24,S013,Respondent interested during the interview\r\n25,S013B,Interview privacy\r\n26,S016,Language of the interview (WVS/EVS list of languages)\r\n27,S016a,Language of the interview (ISO 639-1 alpha-2 / 639-2 alpha-3) \r\n28,S017,Weight\r\n29,S018,Equilibrated weight-1000\r\n30,S019,Equilibrated weight-1500\r\n31,pwght,Population size weight\r\n32,S020,Year survey\r\n33,S021,Country - wave - study - set - year\r\n34,S022,Year/month of start-fieldwork\r\n35,S023,Year/month of end-fieldwork\r\n36,S024,Country - wave\r\n37,S025,Country - year\r\n38,S036,Flag variable: Duplicate Cases\r\n39,mm_fw_end_fu_EVS5,Year/month of end-fieldwork (matrix design) (EVS5)\r\n40,mm_fw_start_fu_EVS5,Year/month of start-fieldwork (matrix design) (EVS5)\r\n41,mm_matrix_group_EVS5,Matrix attribution (group/variable bloc) (EVS5)\r\n42,mm_mixed_mode_EVS5,Mixed mode/matrix design (EVS5)\r\n43,mm_mode_fu_EVS5,Mode of data collection (follow-up) (EVS5)\r\n44,mm_v277_fu_EVS5,Date of interview (follow-up) (EVS5)\r\n45,mm_v278a_fu_r_EVS5,Time of the interview -Start (constructed) (follow-up) (EVS5)\r\n46,mm_v279a_fu_r_EVS5,Time of the interview -End (constructed) (follow-up) (EVS5)\r\n47,mm_year_fu_EVS5,Survey year (follow-up) (EVS5)\r\n48,A001,Important in life: Family\r\n49,A002,Important in life: Friends\r\n50,A003,Important in life: Leisure time\r\n51,A004,Important in life: Politics\r\n52,A005,Important in life: Work\r\n53,A006,Important in life: Religion\r\n54,A007,Important in life: Service to others\r\n55,A008,Feeling of happiness\r\n56,A009,State of health (subjective)\r\n57,A010,Ever felt very excited or interested\r\n58,A011,Ever felt restless\r\n59,A012,Ever felt proud because someone complimented you\r\n60,A013,Ever felt very lonely or remote from other people\r\n61,A014,Ever felt pleased about having accomplished something\r\n62,A015,Ever felt bored\r\n63,A016,Ever felt on top of the world\r\n64,A017,Ever felt depressed or very unhappy\r\n65,A018,Ever felt that things were going your way\r\n66,A019,Ever felt upset because somebody criticized you\r\n72,A025,Respect and love for parents\r\n73,A026,Parents responsibilities to their children\r\n75,A027,Important child qualities: Good manners\r\n77,A029,Important child qualities: independence\r\n78,A030,Important child qualities: Hard work\r\n80,A032,Important child qualities: feeling of responsibility\r\n82,A034,Important child qualities: imagination\r\n83,A035,Important child qualities: tolerance and respect for other people\r\n86,A038,Important child qualities: thrift saving money and things\r\n87,A039,Important child qualities: determination perseverance\r\n88,A040,Important child qualities: religious faith\r\n89,A041,Important child qualities: unselfishness\r\n90,A042,Important child qualities: obedience\r\n92,A043_01,Important child qualities: None\r\n100,A046,Abortion when the mothers health is at risk\r\n101,A047,Abortion when child physically handicapped\r\n102,A048,Abortion when woman not married\r\n103,A049,Abortion if not wanting more children\r\n116,A058,Spend time with friends\r\n117,A059,Spend time with colleagues from work\r\n118,A060,"Spend time with people at your church, mosque or synagogue"\r\n119,A061,"Spend time with people at sport, culture, communal organization"\r\n120,A062,How often discusses political matters with friends\r\n121,A063,"Persuading friends, relatives or fellow workers"\r\n122,A064,"Member: Belong to social welfare service for elderly, handicapped or deprived people"\r\n123,A065,Member: Belong to religious organization\r\n124,A066,"Member: Belong to education, arts, music or cultural activities"\r\n125,A067,Member: Belong to labour unions\r\n126,A068,Member: Belong to political parties\r\n127,A069,Member: Belong to local political actions\r\n128,A070,Member: Belong to human rights\r\n129,A071,"Member: Belong to conservation, the environment, ecology, animal rights"\r\n130,A071B,"Member: Belong to conservation, the environment, ecology"\r\n131,A071C,Member: Belong to animal rights\r\n132,A072,Member: Belong to professional associations\r\n133,A073,Member: Belong to youth work\r\n134,A074,Member: Belong to sports or recreation\r\n135,A075,Member: Belong to women\xb4s group\r\n136,A076,Member: Belong to peace movement\r\n137,A077,Member: Belong to organization concerned with health\r\n138,A078,Member: Belong to consumer groups\r\n139,A079,Member: Belong to other groups\r\n141,A080,Member: Belong to none\r\n142,A080_01,Member: Belong to humanitarian or charitable organization\r\n143,A080_02,"Member:  Belong to self-help group, mutual aid group"\r\n147,A081,"Voluntary work: Unpaid work social welfare service for elderly, handicapped or deprived people"\r\n148,A082,Voluntary work: Unpaid work religious or church organization\r\n149,A083,"Voluntary work: Unpaid work education, arts, music or cultural activities"\r\n150,A084,Voluntary work: Unpaid work labour unions\r\n151,A085,Voluntary work: Unpaid work political parties or groups\r\n152,A086,Voluntary work: Unpaid work local political action groups\r\n153,A087,Voluntary work: Unpaid work human rights\r\n154,A088,"Voluntary work: Unpaid work environment, conservation, animal rights"\r\n155,A088B,"Voluntary work: Unpaid work environment, conservation, ecology"\r\n156,A088C,Voluntary work: Unpaid work animal rights\r\n157,A089,Voluntary work: Unpaid work professional associations\r\n158,A090,Voluntary work: Unpaid work youth work\r\n159,A091,Voluntary work: Unpaid work sports or recreation\r\n160,A092,Voluntary work: Unpaid work women\xb4s group\r\n161,A093,Voluntary work: Unpaid work peace movement\r\n162,A094,Voluntary work: Unpaid work organization concerned with health\r\n164,A096,Voluntary work: Unpaid work other groups\r\n165,A097,Voluntary work: Unpaid work none\r\n168,A098,Active/Inactive membership of church or religious organization\r\n169,A099,Active/Inactive membership of sport or recreation\r\n170,A100,"Active/Inactive membership of art, music, educational"\r\n171,A101,Active/Inactive membership of labour unions\r\n172,A102,Active/Inactive membership of political party\r\n173,A103,Active/Inactive membership of environmental organization\r\n174,A104,Active/Inactive membership of professional organization\r\n175,A105,Active/Inactive membership of charitable/humanitarian organization\r\n176,A106,Active/Inactive membership of any other organization\r\n177,A106B,Active/Inactive membership: Consumer organization\r\n178,A106C,"Active/Inactive membership: Self-help group, mutual aid group"\r\n180,A107,Reasons voluntary work: Solidarity with the poor and disadvantaged\r\n181,A108,Reasons voluntary work: Compassion for those in need\r\n182,A109,Reasons voluntary work: Opportunity to repay something\r\n183,A110,"Reasons voluntary work: Sense of duty, moral, obligation"\r\n184,A111,Reasons voluntary work: Identifying with people who suffer\r\n185,A112,Reasons voluntary work: Time on my hands\r\n186,A113,Reasons voluntary work: Personal satisfaction\r\n187,A114,Reasons voluntary work: Religious belief\r\n188,A115,Reasons voluntary work: Help disadvantaged people\r\n189,A116,Reasons voluntary work: Make a contribution to my local community\r\n190,A117,Reasons voluntary work: Bring about social or political change\r\n191,A118,Reasons voluntary work: For social reasons\r\n192,A119,Reasons voluntary work: Gain new skills and useful experience\r\n193,A120,"Reasons voluntary work: Did not want to, but could not refuse"\r\n197,A124_01,Neighbours: People with a criminal record\r\n198,A124_02,Neighbours: People of a different race\r\n199,A124_03,Neighbours: Heavy drinkers\r\n200,A124_04,Neighbours: Emotionally unstable people\r\n201,A124_05,Neighbours: Muslims\r\n202,A124_06,Neighbours: Immigrants/foreign workers\r\n206,A124_07,Neighbours: People who have AIDS\r\n207,A124_08,Neighbours: Drug addicts\r\n208,A124_09,Neighbours: Homosexuals\r\n209,A124_10,Neighbours: Jews\r\n210,A124_11,Neighbours: Evangelists\r\n211,A124_12,Neighbours: People of a different religion\r\n213,A124_14,Neighbours: Militant minority\r\n215,A124_16,Neighbours: People not from country of origin\r\n216,A124_17,Neighbours: Gypsies\r\n217,A124_18,Neighbours: Political Extremists\r\n218,A124_19,Neighbours: Trafficants\r\n223,A124_24,Neighbours: Christians\r\n225,A124_26,Neighbours: Left wing extremists\r\n226,A124_27,Neighbours: Right wing extremists\r\n227,A124_28,Neighbours: People with large families\r\n228,A124_29,Neighbours: Hindus\r\n229,A124_30,Neighbours: North-American persons\r\n233,A124_34,Neighbours: Black people\r\n234,A124_35,Neighbours: White people\r\n235,A124_36,Neighbours: Coloured people\r\n236,A124_37,Neighbours: Indians\r\n237,A124_38,"Neighbours: Kurds, Esids"\r\n241,A124_42,Neighbours: Unmarried couples living together\r\n242,A124_43,Neighbours: People who speak a different language\r\n243,A124_45,Neighbours: Sunnis\r\n244,A124_46,Neighbours: Shia\r\n245,A124_47,Neighbours: French\r\n246,A124_48,Neighbours: British\r\n247,A124_49,Neighbours: Iranian\r\n248,A124_50,Neighbours: Kuwaiti\r\n249,A124_51,Neighbours: Turkish\r\n250,A124_52,Neighbours: Jordanian\r\n264,A165,Most people can be trusted\r\n267,A168,Do you think most people try to take advantage of you\r\n269,A168A,Do you think most people try to take advantage of you (10-point scale)\r\n270,A169,Good human relationships\r\n271,A170,Satisfaction with your life\r\n274,A173,How much freedom of choice and control\r\n276,A189,Schwartz: It is important to this person to think up new ideas and be creative\r\n277,A190,Schwartz: It is important to this person to be rich\r\n278,A191,Schwartz: It is important to this person living in secure surroundings\r\n279,A192,Schwartz: It is important to this person to have a good time\r\n280,A193,Schwartz: It is important to this person to help the people nearby\r\n281,A194,Schwartz: It is important to this person being very successful\r\n282,A195,Schwartz: It is important to this person adventure and taking risks\r\n283,A196,Schwartz: It is important to this person to always behave properly\r\n284,A197,Schwartz: It is important to this person looking after the environment\r\n285,A198,Schwartz: It is important to this person tradition\r\n310,B001,Would give part of my income for the environment (4-point scale)\r\n313,B002,Increase in taxes if used to prevent environmental pollution\r\n314,B003,Government should reduce environmental pollution\r\n316,B005,All talk about the environment make people anxious\r\n317,B006,"Combatting unemployment, we have to accept environmental problems"\r\n318,B007,Protecting environment and fighting pollution is less urgent than suggested\r\n319,B008,Protecting environment vs. Economic growth\r\n320,B009,Human & nature\r\n347,C001,Jobs scarce: Men should have more right to a job than women (3 categories)\r\n348,C001_01,Jobs scarce: Men should have more right to a job than women (5-point scale)\r\n349,C002,Jobs scarce: Employers should give priority to (nation) people than immigrants (3 categories)\r\n350,C002_01,Jobs scarce: Employers should give priority to (nation) people than immigrants (5-point scale)\r\n352,C004,Jobs scarce: older people should be forced to retire\r\n353,C005,Unfair to give work to handicapped people when able bodied people can\xb4t find jobs\r\n354,C006,Satisfaction with financial situation of household\r\n356,C008,Work compared with Leisure\r\n357,C009,"First choice, if looking for a job"\r\n358,C010,Second choice if looking for a job\r\n359,C011,Important in a job: good pay\r\n360,C012,Important in a job: not too much pressure\r\n361,C013,Important in a job: good job security\r\n362,C014,Important in a job: a respected job\r\n363,C015,Important in a job: good hours\r\n364,C016,Important in a job: an opportunity to use initiative\r\n365,C017,Important in a job: generous holidays\r\n366,C018,Important in a job: that you can achieve something\r\n367,C019,Important in a job: a responsible job\r\n368,C020,Important in a job: a job that is interesting\r\n369,C021,Important in a job: a job that meets one\xb4s abilities\r\n370,C022,Important in a job: pleasant people to work with\r\n371,C023,Important in a job: good chances for promotion\r\n372,C024,Important in a job: a useful job for society\r\n373,C025,Important in a job: meeting people\r\n380,C027_90,Important in a job: none of these\r\n384,C029,Employed\r\n386,C031,Degree of pride in your work\r\n388,C033,Job satisfaction\r\n389,C034,Freedom decision taking in job\r\n391,C036,To develop talents you need to have a job\r\n393,C037,Humiliating to receive money without having to work for it\r\n394,C038,People who don\xb4t work turn lazy\r\n395,C039,Work is a duty towards society\r\n396,C040,People should not have to work if they don\xb4t want to\r\n397,C041,Work should come first even if it means less spare time\r\n398,C042B1,Why people work: work is like a business transaction\r\n399,C042B2,Why people work: I do the best I can regardless of pay\r\n400,C042B3,Why people work: I wouldn\x92t work if I didn\x92t have to\r\n401,C042B4,Why people work: I wouldn\xb4t work if work interfered my life\r\n402,C042B5,Why people work: work most important in my life\r\n403,C042B6,Why people work: I never had a paid job\r\n404,C042B7,Why people work: don\x92t know\r\n416,C059,Fairness: One secretary is paid more\r\n417,C060,How business and industry should be managed\r\n418,C061,Following instructions at work\r\n422,D001,How much do you trust your family (5-point scale)\r\n423,D001_B,How much do you trust your family (4-point scale)\r\n424,D002,Satisfaction with home life\r\n425,D003,Sharing with partner: attitudes towards religion\r\n426,D004,Sharing with partner: moral standards\r\n427,D005,Sharing with partner: social attitudes\r\n428,D006,Sharing with partner: political views\r\n429,D007,Sharing with partner: sexual attitudes\r\n430,D008,Sharing with partner: no sharing attitudes\r\n432,D009,Sharing with partner: don\xb4t know or missing\r\n433,D010,Sharing with parents: attitudes towards religion\r\n434,D011,Sharing with parents: moral standards\r\n435,D012,Sharing with parents: social attitudes\r\n436,D013,Sharing with parents: political views\r\n437,D014,Sharing with parents: sexual attitudes\r\n438,D015,Sharing with parents: no sharing attitudes\r\n440,D016,Sharing with parents: don\xb4t know or missing\r\n441,D017,Ideal number of children\r\n442,D018,Child needs a home with father and mother\r\n443,D019,A woman has to have children to be fulfilled\r\n444,D020,A man has to have children to be fulfilled\r\n446,D022,Marriage is an out-dated institution\r\n447,D023,Woman as a single parent\r\n448,D024,Enjoy sexual freedom\r\n450,D026,Long-term relationship is necessary to be happy\r\n453,D026_03,Duty towards society to have children\r\n455,D026_05,It is childs duty to take care of ill parent\r\n456,D027,Important for successful marriage: Faithfulness\r\n457,D028,Important for successful marriage: Adequate income\r\n458,D029,Important for successful marriage: Same social background\r\n459,D030,Important for successful marriage: Respect and appreciation\r\n460,D031,Important for successful marriage: Religious beliefs\r\n461,D032,Important for successful marriage: Good housing\r\n462,D033,Important for successful marriage: Agreement on politics\r\n463,D034,Important in successful marriage: Understanding and tolerance\r\n464,D035,Important for successful marriage: Apart from in-laws\r\n465,D036,Important for successful marriage: Happy sexual relationship\r\n466,D037,Important for successful marriage: Sharing household chores\r\n467,D038,Important for successful marriage: Children\r\n468,D039,Important in successful marriage: Discussing problems\r\n472,D043,Important for successful marriage: Tastes and interests in common\r\n473,D043_01,Important for successful marriage: Time for friends and personal hobbies\r\n486,D054,One of main goals in life has been to make my parents proud\r\n488,D055,Make effort to live up to what my friends expect\r\n489,D056,Relationship working mother\r\n490,D057,Being a housewife just as fulfilling\r\n491,D058,Husband and wife should both contribute to income\r\n492,D059,Men make better political leaders than women do\r\n494,D060,University is more important for a boy than for a girl\r\n496,D061,Pre-school child suffers with working mother\r\n498,D062,Women want a home and children\r\n500,D063,Job best way for women to be independent (4 categories)\r\n502,D064,Fathers are well suited for looking after children\r\n506,D066_B,Problem if women have more income than husband (B)\r\n518,D078,Men make better business executives than women do\r\n522,D081,Homosexual couples are as good parents as other couples\r\n528,E001,Aims of country: first choice\r\n530,E002,Aims of country: second choice\r\n531,E003,Aims of respondent: first choice\r\n533,E004,Aims of respondent: second choice\r\n534,E005,Most important: first choice\r\n536,E006,Most important: second choice\r\n542,E012,Willingness to fight for country\r\n545,E014,Future changes: Less emphasis on money and material possessions\r\n546,E015,Future changes: Less importance placed on work\r\n547,E016,Future changes: More emphasis on technology\r\n548,E017,Future changes: More emphasis on individual\r\n549,E018,Future changes: Greater respect for authority\r\n550,E019,Future changes: More emphasis on family life\r\n551,E020,Future changes: A simple and more natural lifestyle\r\n553,E022,Opinion about scientific advances\r\n554,E023,Interest in politics\r\n556,E025,Political action: Signing a petition\r\n557,E025B,Political action recently done: signing a petition\r\n558,E026,Political action: joining in boycotts\r\n559,E026B,Political action recently done: joining in boycotts\r\n560,E027,Political action: attending lawful/peaceful demonstrations\r\n561,E028,Political action: joining unofficial strikes\r\n563,E029,Political action: occupying buildings or factories\r\n566,E032,Freedom or equality\r\n567,E033,Self positioning in political scale\r\n568,E034,Basic kinds of attitudes concerning society\r\n569,E035,Income equality\r\n570,E036,Private vs state ownership of business\r\n571,E037,Government responsibility\r\n572,E038,Job taking of the unemployed\r\n573,E039,Competition good or harmful\r\n574,E040,Hard work brings success\r\n575,E041,Wealth accumulation\r\n576,E042,Firms and freedom\r\n579,E045,Major changes in life\r\n580,E046,New and old ideas\r\n581,E047,"Personal characteristics: Changes, worry or welcome possibility"\r\n582,E048,Personal characteristics: I usually count on being successful in everything I do\r\n583,E049,Personal characteristics: I enjoy convincing others of my opinion\r\n584,E050,Personal characteristics: I serve as a model for others\r\n585,E051,Personal characteristics: I am good at getting what I want\r\n586,E052,Personal characteristics: I own many things others envy me for\r\n587,E053,Personal characteristics: I like to assume responsibility\r\n588,E054,Personal characteristics: I am rarely unsure about how I should behave\r\n589,E055,Personal c

In [26]:
labels = pd.read_csv(
    "../data/World_Values_Survey/wvs_labels.CSV", encoding="unicode_escape"
)
labels

,ID,Common Dictionary: Variable name\n\n[Orange cells= variables included in JOINT EVS/WVS\n,Common Dictionary: Variable label\n
0,1.0,studyno,Study number
1,2.0,version,Version
2,3.0,doi,Digital Object Identifier
3,4.0,stdyno_w,Study number (wave)
4,5.0,studyno,Study number
...,...,...,...
1775,NaN,NaN,NaN
1776,NaN,NaN,NaN
1777,NaN,NaN,NaN
1778,NaN,NaN,NaN
1779,NaN,NaN,NaN