In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("https://drive.google.com/uc?id=1oE-3rt17bFW7fOzDIjwFSEMPTIV3NvcO")

## Select Columns

In [ ]:
df["grade_language_t1"] # select column by name
df[["sex", "grade_language_t1"]].head() # select columns by name

   sex  grade_language_t1
0    1           2.369783
1    1           7.206984
2    2           8.057449
3    1           7.388008
4    1           6.773626

###  filter()

In [ ]:
# alternative with extra functionality
df.filter(["sex", "grade_language_t1"])
df.filter(items=["sex", "grade"]) # select columns

# regex filtering
df.filter(regex="^grade", axis=1) # select columns with "grade" at the start of their name
df.filter(regex="t2$", axis=1) # select columns with "t2" at the end

# fuzzy filtering
df.filter(regex="^grade") # all columns that start with 'grade'
df.filter(like="math", axis=1) # select columns with "math" in their name

      grade_math_t1  grade_math_t2
0          2.046285       1.175309
1          7.859077       7.548812
2          7.118976       6.181019
3          6.973737       7.593102
4          6.574877       7.611065
...             ...            ...
1505       4.938375       6.162418
1506       7.661931       8.179364
1507       9.248758       8.773601
1508       5.689228       6.382995
1509       9.768719       9.515601

[1510 rows x 2 columns]

In [ ]:
df.columns

## Index Rows
accessing specific positions (rows/cells)

In [ ]:
# create a new dataframe with a string index
df_name = df[["student_id", "grade_language_t1", "school_id"]].set_index("student_id") # set index to a column
df_name.head()

# loc[] selects by name
df_name.loc["j0ihe@cunb.edu"][['school_id', 'grade_language_t1']] # select row by name

school_id            57.000000
grade_language_t1     7.206984
Name: j0ihe@cunb.edu, dtype: float64

In [ ]:
# iloc[] selects by index
df.iloc[1509][:2]  # happens to the same as name

school_id    946
grade          8
Name: 1509, dtype: object

In [ ]:
# indexing by row/col name 
df_name.at["j0ihe@cunb.edu", "school_id"]  = 9999  # set value of single cell
df_name.at["j0ihe@cunb.edu", "school_id"]  # single cell

df_name["j0ihe@cunb.edu":].head()

                grade_language_t1  school_id
student_id
j0ihe@cunb.edu           7.206984       9999
wcjgk@cunb.edu           8.057449         57
mzmqb@cunb.edu           7.388008         57
s6n0y@cunb.edu           6.773626         57
valwu@cunb.edu           8.237650         57

In [ ]:
# indexing by row/col position
df.iat[1502, 3] = "eohgp-ws@cunb.edu" # update value of single cell
df.iat[1502, 3] # row 1509, col 3 (email)

df[1500:1505]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
1500,946,8,D,qluoj@cunb.edu,1,1,8.028151,7.721704,7.121938,8.315637,8.009190,7.409424,0,1994-09-10
1501,946,8,D,vykat@cunb.edu,1,1,4.184713,4.957843,5.457136,4.862387,5.635517,6.134810,0,1994-12-22
1502,946,8,D,eohgp-ws@cunb.edu,1,1,7.927814,7.530684,8.848721,6.007431,5.610300,6.928337,0,1994-10-16
1503,946,8,D,2hk9v@cunb.edu,1,1,6.553834,6.540934,6.760266,4.893724,4.880824,5.100157,0,1995-02-05
1504,946,8,D,gt35i@cunb.edu,1,1,6.562941,6.272435,6.632548,6.189953,5.899447,6.259560,0,1994-09-11

In [ ]:
df.loc[200:204]  # select rows by name sliced -> from : to
df[200:204]  # select rows by index sliced -> from : to

# names in the index
df_id = df.set_index("student_id", drop=True)
df_id.loc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']]
# df_id.iloc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']] # does not work because iloc only accepts integer positions

df_id[1:4]
df_id.iloc[1:4]

,school_id,grade,class,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
student_id,,,,,,,,,,,,,
j0ihe@cunb.edu,57,6,A,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
wcjgk@cunb.edu,57,6,A,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23
mzmqb@cunb.edu,57,6,A,1,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812,1,1997-02-24

### Slicing
Slicing means getting a range of rows using position

In [ ]:
# slicing rows, columns


# slicing rows and columns with loc
df.loc[:2, ["sex", "school_id"]]  # slice of rows and selection of columns
df.loc[:, "sex": "grade_language_t1"]  # get all row from col 'b' & 'c'
df.loc[1:3, "sex": "grade_language_t1"]  # get rows from : to, of columns from:to
df.loc[1:2, :]  # get rows - from : to & all columns


# slicing rows and columns with iloc
df.iloc[0:3]  # first 3 rows by index
df.iloc[:, -1]  # select last column by index
df.iloc[0:3, :]  #  Slicing Rows and Columns by position
df.iloc[:, 0:3]  # slice columns by index position.
df.iloc[0:2, 1:3]  # slice row and columns by index position.
df.iloc[:2, :2]  # row index 0 to index 1 (exclusive 2), column zero to one

df.iloc[0:20:4, 0:4]  # row index 0 to 20 (step 4), column index 0 to 4
df.iloc[10::-1] # reverse the order of rows from index 10 to the beginning

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
10,57,6,A,hsnzr@cunb.edu,1,1,6.262377,5.767466,4.669702,6.059770,5.564859,4.467095,1,1997-02-28
9,57,6,A,crjpx@cunb.edu,1,1,9.039362,9.126943,8.789369,8.235168,8.322749,7.985175,1,1996-10-24
8,57,6,A,nfljw@cunb.edu,1,2,5.336137,5.238938,4.819695,6.393512,6.296313,5.877070,1,1997-08-07
7,57,6,A,pakza@cunb.edu,1,2,6.025744,5.383473,7.036745,6.820959,6.178687,7.831960,1,1997-02-09
6,57,6,A,ylw2t@cunb.edu,1,1,8.611935,8.015355,9.277730,7.635252,7.038671,8.301046,1,1997-04-23
5,57,6,A,valwu@cunb.edu,1,1,7.041647,8.237650,7.133128,6.269658,7.465661,6.361139,1,1997-06-18
4,57,6,A,s6n0y@cunb.edu,1,1,6.574877,6.773626,7.844316,7.611065,7.809814,8.880504,1,1996-09-05
3,57,6,A,mzmqb@cunb.edu,1,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812,1,1997-02-24
2,57,6,A,wcjgk@cunb.edu,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23
1,57,6,A,j0ihe@cunb.edu,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
0,57,6,A,wvqgd@cunb.edu,1,1,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368,1,1997-07-27