# Selection, Indexing, Filtering

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://drive.google.com/uc?id=1oE-3rt17bFW7fOzDIjwFSEMPTIV3NvcO")

## Select Columns

In [3]:
df["grade_language_t1"] # select column by name
df[["sex", "grade_language_t1"]].head() # select columns by name

   sex  grade_language_t1
0    1           2.369783
1    1           7.206984
2    2           8.057449
3    1           7.388008
4    1           6.773626

###  filter()

In [6]:
# alternative with extra functionality
df.filter(["sex", "grade_language_t1"])
df.filter(items=["sex", "grade"]) # select columns
df.filter(regex="^grade", axis=1) # select columns with "grade" at the start of their name
df.filter(regex="t2$", axis=1) # select columns with "t2" at the end
df.filter(like="math", axis=1) # select columns with "math" in their name
df.filter(regex="^grade") # all columns that start with 'grade'

,grade,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2
0,6,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368
1,6,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190
2,6,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253
3,6,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812
4,6,6.574877,6.773626,7.844316,7.611065,7.809814,8.880504
...,...,...,...,...,...,...,...
1505,8,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960
1506,8,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598
1507,8,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484
1508,8,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315
1509,8,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953

## Index Rows
accessing specific positions (rows/cells)

In [8]:
# loc[] selects by name
df.loc[1509][['school_id', 'grade']] # select row by name

school_id    946
grade          8
Name: 1509, dtype: object

In [10]:
# iloc[] selects by index
df.iloc[1509][:2]  # happens to the same as name

school_id    946
grade          8
Name: 1509, dtype: object

In [12]:
# indexing by row/col name 
df.at[1509, "school_id"]  = 9999  # set value of single cell
df.at[1509, "school_id"]  # single cell

np.int64(9999)

In [ ]:
# indexing by row/col position
df.iat[1509, 3] = "eohgp-ws@cunb.edu" # update value of single cell
df.iat[1509, 3] # row 1509, col 3 (email)

'eohgp-ws@cunb.edu'

In [ ]:
df.loc[200:204]  # select rows by name sliced -> from : to
df[200:204]  # select rows by index sliced -> from : to

# names in the index
df_id = df.set_index("student_id", drop=True)
df_id.loc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']]
# df_id.iloc[['j0ihe@cunb.edu', 'mzmqb@cunb.edu']] # does not work because iloc only accepts integer positions

df_id[1:4]
df_id.iloc[1:4]

,school_id,grade,class,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
student_id,,,,,,,,,,,,,
j0ihe@cunb.edu,57,6,A,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
wcjgk@cunb.edu,57,6,A,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23
mzmqb@cunb.edu,57,6,A,1,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812,1,1997-02-24

### Slicing
Slicing means getting a range of rows using position

In [ ]:
df.iloc[0:3]  # first 3 rows by index
# slicing rows, columns
df.loc[:2, ["sex", "school_id"]]  # slice of rows and selection of columns
df.loc[:, "sex": "grade_language_t1"]  # get all row from col 'b' & 'c'
df.loc[1:3, "sex": "grade_language_t1"]  # get rows from : to, of columns from:to
df.loc[1:2, :]  # get rows - from : to & all columns
df.iloc[:, -1]  # select last column by index
df.iloc[0:3, :]  #  Slicing Rows and Columns by position
df.iloc[:, 0:3]  # slice columns by index position.
df.iloc[0:2, 1:3]  # slice row and columns by index position.
df.iloc[:2, :2]  # row index 0 to index 1 (exclusive 2), column zero to one

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
0,57,6,A,wvqgd@cunb.edu,1,1,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368,1,1997-07-27
1,57,6,A,j0ihe@cunb.edu,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
2,57,6,A,wcjgk@cunb.edu,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23

## Boolean Indexing

In [ ]:
# df[df["school_id"] == 57]
df[df["school_id"].isin([57, 141])] # multiple values in a column
df[df["date_of_birth"]>"1995-01-01"] # greater than
df[(df["grade_math_t1"] > 9) | (df["school_id"] == 57)] # or
df[(df["grade_math_t1"] > 9) & (df["school_id"] == 57)] # and

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
9,57,6,A,crjpx@cunb.edu,1,1,9.039362,9.126943,8.789369,8.235168,8.322749,7.985175,1,1996-10-24
18,57,6,B,gca3x@cunb.edu,1,1,9.150260,9.432889,8.127485,9.523394,9.806023,8.500619,0,1997-07-05
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.000000,10.000000,9.194739,1,1997-03-25
81,57,7,C,ysvls@cunb.edu,1,1,9.604527,8.388494,9.063802,10.000000,9.936316,10.000000,0,1996-07-29
88,57,7,C,7pojk@cunb.edu,1,1,9.267352,8.130984,8.006577,10.000000,9.512149,9.387742,0,1996-02-26
90,57,7,D,pa9yf@cunb.edu,1,1,9.347091,9.207399,8.718461,9.562590,9.422897,8.933960,1,1996-03-21
97,57,7,D,tqgis@cunb.edu,1,1,10.000000,8.995439,8.505144,10.000000,10.000000,9.760000,1,1995-09-04

### between() and loc[] with boolean indexing

In [66]:
# between function
df[df["grade_language_t1"].between(8.6, 8.7)]


# loc with boolean indexing and choosing columns
df.loc[df.grade_language_t1 > 9, ["school_id", "grade"]] 
df[df.grade_language_t1 > 9][["school_id", "grade"]]

      school_id  grade
9            57      6
18           57      6
19           57      6
31           57      6
39           57      6
...         ...    ...
1439        946      7
1464        946      8
1471        946      8
1482        946      8
1509       9999      8

[108 rows x 2 columns]

### isin() and query() methods

In [ ]:
# if values is a list check whether every value in the DataFrame is present in the list
df[df.isin([57, 0])] 

# check specific column for multiple values
df[df.grade.isin([6, 7])]

# check specific column for multiple values and negate the condition
df[~df.grade.isin([6, 7])]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
99,57,8,A,dmv6n@cunb.edu,2,1,4.381631,4.923144,5.650331,4.544731,5.086245,5.813431,0,1995-06-28
100,57,8,A,6gola@cunb.edu,2,1,4.959964,5.541407,5.815619,4.208131,4.789574,5.063786,0,1995-04-01
101,57,8,A,k8gox@cunb.edu,2,2,8.688758,7.802415,7.196903,8.310800,7.424457,6.818945,0,1995-05-24
102,57,8,A,dskjb@cunb.edu,2,1,5.965422,6.225083,4.964288,5.603122,5.862782,4.601988,0,1995-01-22
103,57,8,A,1krmv@cunb.edu,2,1,5.488107,6.166542,5.126704,4.649922,5.328358,4.288519,0,1994-09-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,946,8,D,jj36e@cunb.edu,1,1,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960,0,1995-07-04
1506,946,8,D,ca1dg@cunb.edu,1,1,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598,0,1995-08-23
1507,946,8,D,amdrx@cunb.edu,1,1,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484,0,1994-12-15
1508,946,8,D,yn5ug@cunb.edu,1,2,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315,0,1994-09-18
1509,9999,8,A,eohgp-ws@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19

### query()

In [83]:
df[df.grade_math_t1 > df.grade_math_t2]
df.query("grade_math_t1 > grade_math_t2")[["grade_math_t1", "grade_math_t2"]].round(2)

      grade_math_t1  grade_math_t2
0              2.05           1.18
1              7.86           7.55
2              7.12           6.18
5              7.04           6.27
6              8.61           7.64
...             ...            ...
1502           7.93           6.01
1503           6.55           4.89
1504           6.56           6.19
1507           9.25           8.77
1509           9.77           9.52

[606 rows x 2 columns]

In [86]:
# query can be cleaner for complex queries - keyword class needs backticks in query
# df[(df.sex == 1) & (df["class"] == "C") & ((df.grade_math_t1 > 9.9) | (df.grade_math_t2 > 9.9))]
df.query("sex == 1 & `class` == 'C' & (grade_math_t1 > 9.9 | grade_math_t2 > 9.9)")

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.0,10.000000,9.194739,1,1997-03-25
35,57,6,C,wbcfx@cunb.edu,1,2,6.940615,6.494307,6.535804,10.0,9.664280,9.705778,1,1996-10-24
81,57,7,C,ysvls@cunb.edu,1,1,9.604527,8.388494,9.063802,10.0,9.936316,10.000000,0,1996-07-29
88,57,7,C,7pojk@cunb.edu,1,1,9.267352,8.130984,8.006577,10.0,9.512149,9.387742,0,1996-02-26
137,57,8,C,yxxfv@cunb.edu,1,1,8.631280,8.390752,8.124870,10.0,10.000000,10.000000,1,1995-06-03
373,141,7,C,6zo9s@cunb.edu,1,2,9.207145,8.833523,8.292497,10.0,10.000000,10.000000,1,1996-05-05
383,141,7,C,2hbgs@cunb.edu,1,2,7.348327,6.862350,5.577604,10.0,10.000000,9.297259,1,1996-01-14
419,141,8,C,144ga@cunb.edu,1,1,9.237515,10.000000,8.414176,10.0,10.000000,9.433997,0,1994-11-12
421,141,8,C,5xeof@cunb.edu,1,1,9.135011,8.841103,9.407451,10.0,9.866440,10.000000,0,1994-12-29
527,262,7,C,nq45z@cunb.edu,1,1,8.823036,8.724362,8.356688,10.0,10.000000,9.864914,1,1996-08-15
579,262,8,C,inrty@cunb.edu,1,1,8.504132,8.737318,7.577565,10.0,10.000000,9.576957,0,1995-06-03
669,426,7,C,gxssl@cunb.edu,1,1,8.926202,8.583355,9.375213,10.0,9.668802,10.000000,0,1996-08-18
671,426,7,C,mseow@cunb.edu,1,1,8.231856,9.280767,7.712725,10.0,10.000000,9.669151,0,1996-03-30
733,426,8,C,kdlts@cunb.edu,1,2,7.468656,8.414136,9.020312,10.0,10.000000,10.000000,1,1994-11-19
970,499,7,C,arw8m@cunb.edu,1,1,9.624094,8.536750,9.622638,10.0,9.841537,10.000000,1,1996-07-20
971,499,7,C,rsvdo@cunb.edu,1,2,7.750984,7.710657,9.417058,10.0,10.000000,10.000000,1,1995-12-29
974,499,7,C,e8ypj@cunb.edu,1,2,7.050909,6.689119,6.588267,10.0,10.000000,10.000000,1,1996-03-29
976,499,7,C,x016s@cunb.edu,1,1,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,1,1996-03-28
1082,812,6,C,nye4a@cunb.edu,1,1,9.561568,10.000000,10.000000,10.0,10.000000,10.000000,1,1997-03-09
1135,812,7,C,ujwt4@cunb.edu,1,1,9.046869,8.313388,9.353481,10.0,9.420835,10.000000,1,1996-08-24
1136,812,7,C,2wfqx@cunb.edu,1,1,9.223794,8.957487,9.851779,10.0,10.000000,10.000000,1,1996-05-29
1239,881,6,C,maxy2@cunb.edu,1,1,8.930415,9.212198,8.912495,10.0,10.000000,10.000000,1,1997-03-15

### xs() 
Return cross-section from a particular level of a MultiIndex.

In [92]:
d = {
     "num_legs": [4, 4, 2, 2],
     "num_wings": [0, 0, 2, 2],
     "class": ["mammal", "mammal", "mammal", "bird"],
     "animal": ["cat", "dog", "bat", "penguin"],
     "locomotion": ["walks", "walks", "flies", "walks"],
 }

df = pd.DataFrame(data=d)
# three index levels
df = df.set_index(["class", "animal", "locomotion"])
df.sort_index(level=2, inplace=True)  # sort by first index level
df

                           num_legs  num_wings
class  animal  locomotion
mammal bat     flies              2          2
bird   penguin walks              2          2
mammal cat     walks              4          0
       dog     walks              4          0

In [97]:
df.xs("mammal") # get all mammals
df.xs(("mammal", "dog")) # get all info about dogs
df.xs(("mammal", "dog", "walks")) # get specific info about dogs

/tmp/ipykernel_30595/1720633188.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  df.xs(("mammal", "dog")) # get all info about dogs

num_legs     4
num_wings    0
Name: (mammal, dog, walks), dtype: int64

In [ ]:

# axis=1 means columns
df.xs("num_wings", axis=1) # returns this column


df.xs("mammal", level=0) # level of the index
df.xs("dog", level="animal")

# multiple levels one by index and one by name
df.xs(("bird", "walks"), level=[0, "locomotion"])