# Selection, Indexing, Filtering

### sorting

In [17]:
df.sort_values(by="school_id", ascending=True) # sort by column
df.sort_values(by=["school_id", "grade_language_t1"], ascending=[True, False]) # sort by multiple columns

df.sort_index() # sort by index
df.sort_index(ascending=False) # sort by index in descending order

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth,rank
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.000000,10.000000,9.194739,1,1997-03-25,1.0
1464,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19,1.0
451,262,6,A,swejn@cunb.edu,1,1,10.000000,10.000000,9.368304,10.000000,10.000000,9.377335,1,1997-03-26,1.0
1082,812,6,C,nye4a@cunb.edu,1,1,9.561568,10.000000,10.000000,10.000000,10.000000,10.000000,1,1997-03-09,1.0
1190,812,8,C,gdt3t@cunb.edu,1,1,8.528551,10.000000,9.781599,7.673200,9.144649,8.926248,0,1994-11-13,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,458,6,C,y8d1g@cunb.edu,1,2,0.000000,1.332429,0.000000,0.000000,0.000000,0.000000,0,1997-03-12,1486.0
1261,881,7,A,pm1p8@cunb.edu,1,1,1.247593,1.262528,2.709209,0.415647,0.430582,1.877262,0,1995-09-11,1487.0
965,499,7,C,lqmmt@cunb.edu,1,1,1.630344,1.212652,2.531448,2.886153,2.468461,3.787257,1,1996-06-29,1488.0
656,426,7,A,f6btr@cunb.edu,1,2,1.565799,1.084899,1.630079,1.329981,0.849082,1.394261,0,1996-05-15,1489.0
303,141,6,B,ydca8@cunb.edu,1,1,2.679972,0.993821,0.920921,0.991779,0.000000,0.000000,0,1996-11-02,1490.0

### nlargest, nsmallest, rank

In [ ]:
df.nlargest(5, "grade_language_t1") # top 5 rows with largest values in column
df.nsmallest(5, "grade_language_t1") # top 5 rows with smallest values in column

df["rank"] = df["grade_language_t1"].rank(ascending=False, method='dense') # add a new column with rank based on another column
df.sort_values(by="rank")

In [31]:
df.sample(3) # random sample of 10 rows

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
222,60,7,B,5vm3w@cunb.edu,1,1,4.776980,5.619038,6.048657,5.625962,6.468019,6.897639,1,1996-02-16
1050,499,8,D,rxf7l@cunb.edu,1,1,2.023554,1.692102,3.056696,3.451593,3.120141,4.484735,0,1994-12-20
902,499,6,B,c5qv9@cunb.edu,1,1,4.375106,4.305136,5.374559,5.144623,5.074653,6.144076,1,1997-05-03

### value_counts() 
for categorical columns

In [30]:
df.value_counts("school_id") # count unique values in a column

school_id
499    161
262    158
426    156
812    153
881    153
57     151
946    150
141    146
60     143
458    139
Name: count, dtype: int64

## Boolean Indexing

In [ ]:
df[df["school_id"] == 57] # filter rows by column value
df[df["school_id"].isin([57, 141])] # multiple values in a column
df[df["date_of_birth"]>"1995-01-01"] # greater than
df[(df["grade_math_t1"] > 9) | (df["school_id"] == 57)] # or
df[(df["grade_math_t1"] > 9) & (df["school_id"] == 57)] # and

# boolean indexing and choosing columns
df[df.grade_language_t1 > 9][["school_id", "grade"]]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
9,57,6,A,crjpx@cunb.edu,1,1,9.039362,9.126943,8.789369,8.235168,8.322749,7.985175,1,1996-10-24
18,57,6,B,gca3x@cunb.edu,1,1,9.150260,9.432889,8.127485,9.523394,9.806023,8.500619,0,1997-07-05
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.000000,10.000000,9.194739,1,1997-03-25
81,57,7,C,ysvls@cunb.edu,1,1,9.604527,8.388494,9.063802,10.000000,9.936316,10.000000,0,1996-07-29
88,57,7,C,7pojk@cunb.edu,1,1,9.267352,8.130984,8.006577,10.000000,9.512149,9.387742,0,1996-02-26
90,57,7,D,pa9yf@cunb.edu,1,1,9.347091,9.207399,8.718461,9.562590,9.422897,8.933960,1,1996-03-21
97,57,7,D,tqgis@cunb.edu,1,1,10.000000,8.995439,8.505144,10.000000,10.000000,9.760000,1,1995-09-04

### between()

In [ ]:
# between function
df[df["grade_language_t1"].between(8.6, 8.7)]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
152,60,6,A,s23zr@cunb.edu,1,1,7.469003,8.627791,7.154632,6.778225,7.937013,6.463854,1,1996-09-07
225,60,7,B,itqg3@cunb.edu,1,1,9.106654,8.692597,7.857129,10.000000,NaN,8.771955,1,1996-01-12
271,60,8,C,wvkjj@cunb.edu,1,1,8.443494,8.605681,9.161432,9.017284,9.179470,9.735222,1,1995-06-19
394,141,8,A,3cxlm@cunb.edu,1,1,9.392243,8.689425,8.462716,9.592027,8.889209,8.662500,0,1995-01-21
435,141,8,D,nbfqh@cunb.edu,1,1,8.042715,8.692511,7.029559,7.471731,8.121527,6.458575,1,1994-11-04
660,426,7,B,bgojz@cunb.edu,1,1,7.698128,8.623056,8.413771,8.186171,9.111100,8.901814,0,1996-02-29
706,426,8,A,abtv2@cunb.edu,1,1,8.378432,8.620722,8.213867,8.369673,8.611964,8.205108,0,1994-10-05
905,499,6,B,d56on@cunb.edu,1,1,8.890686,8.687258,9.145725,7.337799,7.134370,7.592837,1,1997-01-01
938,499,7,A,puggl@cunb.edu,1,1,7.586579,8.659088,8.622892,8.407040,9.479549,9.443352,1,1995-11-02
1000,499,8,A,cogby@cunb.edu,1,1,8.246118,8.611387,9.494171,9.555289,9.920558,10.000000,1,1995-07-09
1030,499,8,C,ddcon@cunb.edu,2,1,9.043050,8.644384,8.767195,10.000000,10.000000,10.000000,0,1994-10-13
1102,812,7,A,mspzu@cunb.edu,1,1,7.945537,8.618981,9.088653,9.839512,10.000000,10.000000,1,1995-11-11
1104,812,7,A,h1oms@cunb.edu,1,1,8.033790,8.683016,9.301789,8.310576,8.959802,9.578575,1,1996-03-21
1116,812,7,B,0pym6@cunb.edu,1,1,8.996996,8.626216,8.047691,9.024135,8.653354,8.074830,1,1996-03-11
1145,812,7,D,fgs6y@cunb.edu,1,1,7.338693,8.646809,7.513661,6.217257,7.525373,6.392226,0,1996-08-12
1154,812,8,A,grryf@cunb.edu,1,1,7.573383,8.622292,7.310913,9.113572,10.000000,8.851102,0,1995-07-23
1177,812,8,B,o4zem@cunb.edu,1,1,8.356313,8.624096,8.459241,9.193652,9.461434,9.296580,1,1995-01-20
1198,812,8,C,yrw1j@cunb.edu,1,1,7.894335,8.670669,8.196304,8.502821,9.279154,8.804789,0,1994-11-22
1273,881,7,A,zpf8o@cunb.edu,1,1,7.249717,8.687576,7.800848,7.304209,8.742068,7.855340,0,1995-12-18
1292,881,7,C,e2fta@cunb.edu,2,1,8.643393,8.673983,7.723217,8.328929,8.359519,7.408753,0,1996-02-01
1450,946,8,A,23zxo@cunb.edu,2,1,9.115907,8.602313,9.166211,10.000000,9.641834,10.000000,0,1995-06-15

### isin()

In [ ]:
# if values is a list check whether every value in the DataFrame is present in the list
df[df.isin([57, 0])] 

# check specific column for multiple values
df[df.grade.isin([6, 7])]

# check specific column for multiple values and negate the condition
df[~df.grade.isin([6, 7])]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
99,57,8,A,dmv6n@cunb.edu,2,1,4.381631,4.923144,5.650331,4.544731,5.086245,5.813431,0,1995-06-28
100,57,8,A,6gola@cunb.edu,2,1,4.959964,5.541407,5.815619,4.208131,4.789574,5.063786,0,1995-04-01
101,57,8,A,k8gox@cunb.edu,2,2,8.688758,7.802415,7.196903,8.310800,7.424457,6.818945,0,1995-05-24
102,57,8,A,dskjb@cunb.edu,2,1,5.965422,6.225083,4.964288,5.603122,5.862782,4.601988,0,1995-01-22
103,57,8,A,1krmv@cunb.edu,2,1,5.488107,6.166542,5.126704,4.649922,5.328358,4.288519,0,1994-09-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,946,8,D,jj36e@cunb.edu,1,1,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960,0,1995-07-04
1506,946,8,D,ca1dg@cunb.edu,1,1,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598,0,1995-08-23
1507,946,8,D,amdrx@cunb.edu,1,1,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484,0,1994-12-15
1508,946,8,D,yn5ug@cunb.edu,1,2,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315,0,1994-09-18
1509,9999,8,A,eohgp-ws@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19

### query()

In [85]:
df[df.grade_math_t1 > df.grade_math_t2]
df.query("grade_math_t1 > grade_math_t2")[["grade_math_t1", "grade_math_t2"]].round(2)

      grade_math_t1  grade_math_t2
0              2.05           1.18
1              7.86           7.55
2              7.12           6.18
5              7.04           6.27
6              8.61           7.64
...             ...            ...
1502           7.93           6.01
1503           6.55           4.89
1504           6.56           6.19
1507           9.25           8.77
1509           9.77           9.52

[606 rows x 2 columns]

### query in sql for comparison

In [79]:
from pandasql import sqldf

# Define a helper function for SQL queries
def query(q):
    return sqldf(q, globals())

In [ ]:
result = query("""
    SELECT 
        ROUND(grade_math_t1) as grade_math_t1, 
        ROUND(grade_math_t2) as grade_math_t2,
    FROM df
    WHERE grade_math_t1 > grade_math_t2
""")

result

     grade_math_t1  grade_math_t2
0              2.0            1.0
1              8.0            8.0
2              7.0            6.0
3              7.0            6.0
4              9.0            8.0
..             ...            ...
601            8.0            6.0
602            7.0            5.0
603            7.0            6.0
604            9.0            9.0
605           10.0           10.0

[606 rows x 2 columns]

In [86]:
# query can be cleaner for complex queries - keyword class needs backticks in query
# df[(df.sex == 1) & (df["class"] == "C") & ((df.grade_math_t1 > 9.9) | (df.grade_math_t2 > 9.9))]
df.query("sex == 1 & `class` == 'C' & (grade_math_t1 > 9.9 | grade_math_t2 > 9.9)")

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.0,10.000000,9.194739,1,1997-03-25
35,57,6,C,wbcfx@cunb.edu,1,2,6.940615,6.494307,6.535804,10.0,9.664280,9.705778,1,1996-10-24
81,57,7,C,ysvls@cunb.edu,1,1,9.604527,8.388494,9.063802,10.0,9.936316,10.000000,0,1996-07-29
88,57,7,C,7pojk@cunb.edu,1,1,9.267352,8.130984,8.006577,10.0,9.512149,9.387742,0,1996-02-26
137,57,8,C,yxxfv@cunb.edu,1,1,8.631280,8.390752,8.124870,10.0,10.000000,10.000000,1,1995-06-03
373,141,7,C,6zo9s@cunb.edu,1,2,9.207145,8.833523,8.292497,10.0,10.000000,10.000000,1,1996-05-05
383,141,7,C,2hbgs@cunb.edu,1,2,7.348327,6.862350,5.577604,10.0,10.000000,9.297259,1,1996-01-14
419,141,8,C,144ga@cunb.edu,1,1,9.237515,10.000000,8.414176,10.0,10.000000,9.433997,0,1994-11-12
421,141,8,C,5xeof@cunb.edu,1,1,9.135011,8.841103,9.407451,10.0,9.866440,10.000000,0,1994-12-29
527,262,7,C,nq45z@cunb.edu,1,1,8.823036,8.724362,8.356688,10.0,10.000000,9.864914,1,1996-08-15
579,262,8,C,inrty@cunb.edu,1,1,8.504132,8.737318,7.577565,10.0,10.000000,9.576957,0,1995-06-03
669,426,7,C,gxssl@cunb.edu,1,1,8.926202,8.583355,9.375213,10.0,9.668802,10.000000,0,1996-08-18
671,426,7,C,mseow@cunb.edu,1,1,8.231856,9.280767,7.712725,10.0,10.000000,9.669151,0,1996-03-30
733,426,8,C,kdlts@cunb.edu,1,2,7.468656,8.414136,9.020312,10.0,10.000000,10.000000,1,1994-11-19
970,499,7,C,arw8m@cunb.edu,1,1,9.624094,8.536750,9.622638,10.0,9.841537,10.000000,1,1996-07-20
971,499,7,C,rsvdo@cunb.edu,1,2,7.750984,7.710657,9.417058,10.0,10.000000,10.000000,1,1995-12-29
974,499,7,C,e8ypj@cunb.edu,1,2,7.050909,6.689119,6.588267,10.0,10.000000,10.000000,1,1996-03-29
976,499,7,C,x016s@cunb.edu,1,1,10.000000,10.000000,10.000000,10.0,10.000000,10.000000,1,1996-03-28
1082,812,6,C,nye4a@cunb.edu,1,1,9.561568,10.000000,10.000000,10.0,10.000000,10.000000,1,1997-03-09
1135,812,7,C,ujwt4@cunb.edu,1,1,9.046869,8.313388,9.353481,10.0,9.420835,10.000000,1,1996-08-24
1136,812,7,C,2wfqx@cunb.edu,1,1,9.223794,8.957487,9.851779,10.0,10.000000,10.000000,1,1996-05-29
1239,881,6,C,maxy2@cunb.edu,1,1,8.930415,9.212198,8.912495,10.0,10.000000,10.000000,1,1997-03-15

### xs() 
Return cross-section from a particular level of a MultiIndex.

In [90]:
d = {
     "num_legs": [4, 4, 2, 2],
     "num_wings": [0, 0, 2, 2],
     "class": ["mammal", "mammal", "mammal", "bird"],
     "animal": ["cat", "dog", "bat", "penguin"],
     "locomotion": ["walks", "walks", "flies", "walks"],
 }

df = pd.DataFrame(data=d)
df = df.set_index(["class", "animal", "locomotion"])
df

                           num_legs  num_wings
class  animal  locomotion
mammal cat     walks              4          0
       dog     walks              4          0
       bat     flies              2          2
bird   penguin walks              2          2

In [105]:
# three index levels
df.sort_index(inplace=True)  # sort by first index level
df

                           num_legs  num_wings
class  animal  locomotion
bird   penguin walks              2          2
mammal bat     flies              2          2
       cat     walks              4          0
       dog     walks              4          0

In [106]:
df.xs("mammal") # get all mammals
df.xs(("mammal", "dog")) # get all info about dogs
df.xs(("mammal", "bat")) # get specific info about dogs

            num_legs  num_wings
locomotion
flies              2          2

In [ ]:

df.xs("cat", level=1) # get all animals that are cats
df.xs("walks", level=2) # get all animals that walk

In [ ]:

# axis=1 means columns
df.xs("num_wings", axis=1) # returns this column


df.xs("mammal", level=0) # level of the index
df.xs("dog", level="animal")

# multiple levels one by index and one by name
df.xs(("bird", "walks"), level=[0, "locomotion"])