# Data Cleaning

<details><summary>Content</summary>

Handling missing data: .isnull(), .notnull(), .dropna(), .fillna(), .ffill(), .bfill()

Duplicates: .duplicated(), .drop_duplicates()

Replacing values: .replace()

Data type conversion: .astype()

Renaming: .rename(), setting column names directly

String operations: .str accessor methods

What to add:

Dealing with outliers

Converting dates: pd.to_datetime()

Categorical data: .astype('category')

.clip() for value bounds

.unique(), .nunique(), .value_counts()
</details>

<details><summary>Data Cleaning methods</summary>

`df.columns = ['a', 'b', 'c']` # Renames columns

`df.isnull()` # checks for null Values, Returns Boolean Array

`df.notnull()` # Opposite of pd.isnull()

`df.dropna()` # Drops all rows that contain null values

`df.dropna(axis=1)` # Drops all COLUMNS that contain null values

`df.dropna(axis=1, thresh=n)` # Drops all rows have have less than n non-null values

`df.fillna(x)` # Replaces all null values with x

`df.fillna(s.mean())` # Replaces all null values with the mean, median etc.

`df.astype(float)` # Converts the datatype of the Series to float

`df.replace(1, 'one')` # Replaces all values equal to 1 with one

`df.replace([1, 3], ['one','three'])` # Replaces all 1 with 'one' and 3 with 'three'

`df.columns.str.replace("grade_", "")` # renames columns

`df.rename(columns=lambda x: x + 1)` # Mass renaming of columns

`df.rename(columns={'old_name': 'new_name'})` # Selective renaming of columns

`df.rename(index=lambda x: x + 1)` # Mass renaming of index

`df.set_index('column_one')` # Selectively sets the index

</details>

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://drive.google.com/uc?id=1oE-3rt17bFW7fOzDIjwFSEMPTIV3NvcO")
df[:3]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
0,57,6,A,wvqgd@cunb.edu,1,1,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368,1,1997-07-27
1,57,6,A,j0ihe@cunb.edu,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
2,57,6,A,wcjgk@cunb.edu,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23

In [ ]:
# len(df) # no. of rows
# df.describe()  # Basic descriptive statistics for each column (or GroupBy)
# df.info()
# df.shape
# df.dtypes # check data types in df
# df.school_id.nunique()
# df.school_id.unique()
# df.school_id.value_counts()  # count number of rows per school_id

array([ 57,  60, 141, 262, 426, 458, 499, 812, 881, 946])

In [ ]:
df.memory_usage(deep=True)["school_id"] # memory usage in bytes
df["school_id"].astype("category").memory_usage(deep=True)

1722

## Inspection

In [19]:
df.columns
df.shape
# df.info()
df.describe()

,school_id,grade,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment
count,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1510.000000,1508.000000,1507.000000,1508.000000,1510.000000
mean,457.321192,7.037086,1.203311,1.195364,6.653575,6.628136,6.642331,205.855164,139.605428,205.836261,0.501325
std,315.676789,0.817277,0.402595,0.396612,1.701152,1.713346,1.698250,4456.943949,3641.496348,4456.944784,0.500164
min,57.000000,6.000000,1.000000,1.000000,0.000000,0.993821,0.000000,0.000000,0.000000,0.000000,0.000000
25%,141.000000,6.000000,1.000000,1.000000,5.563173,5.530065,5.472154,5.635373,5.601699,5.676830,0.000000
50%,458.000000,7.000000,1.000000,1.000000,6.829838,6.775808,6.757819,7.105604,7.058270,7.024505,1.000000
75%,812.000000,8.000000,1.000000,1.000000,7.943985,7.852015,7.921141,8.386922,8.358125,8.406066,1.000000
max,946.000000,8.000000,2.000000,2.000000,10.000000,10.000000,10.000000,99999.000000,99999.000000,99999.000000,1.000000

In [30]:
df.groupby("school_id").max() # get max values for each column in each group
# df.groupby("school_id")["grade_science_t1"].max()
df.groupby("school_id")[["grade_science_t1", "grade_math_t1"]].max()

           grade_science_t1  grade_math_t1
school_id
57                 9.315957      10.000000
60                10.000000       9.624970
141                9.684803       9.624260
262               10.000000      10.000000
426                9.800801       9.700488
458               10.000000       9.726741
499               10.000000      10.000000
812               10.000000       9.602780
881               10.000000       9.966778
946                9.495653      10.000000

In [ ]:
df.groupby("school_id").count() # count of row per school
round(df_a.math_t1.mean(), 2)
df.math_t2.agg(["min", "max"])
df.math_t2.max()
df.math_t2.sort_values().tail(10)
df.math_t2.sort_values(ascending=False).head(10)
df.language_t1.sort_values(ascending=False).tail(10)
df.language_t2.sort_values(ascending=False).head(10)

## replace()

In [6]:
df.columns = df.columns.str.replace("grade_", "")
df

,school_id,grade,class,student_id,sex,nationality,math_t1,language_t1,science_t1,math_t2,language_t2,science_t2,treatment,date_of_birth
0,57,6,A,wvqgd@cunb.edu,1,1,2.046285,2.369783,2.711344,1.175309,1.498807,1.840368,1,1997-07-27
1,57,6,A,j0ihe@cunb.edu,1,2,7.859077,7.206984,6.994455,7.548812,6.896719,6.684190,1,1997-06-24
2,57,6,A,wcjgk@cunb.edu,2,1,7.118976,8.057449,8.573210,6.181019,7.119492,7.635253,1,1997-04-23
3,57,6,A,mzmqb@cunb.edu,1,1,6.973737,7.388008,6.628448,7.593102,8.007373,7.247812,1,1997-02-24
4,57,6,A,s6n0y@cunb.edu,1,1,6.574877,6.773626,7.844316,7.611065,7.809814,8.880504,1,1996-09-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,946,8,D,jj36e@cunb.edu,1,1,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960,0,1995-07-04
1506,946,8,D,ca1dg@cunb.edu,1,1,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598,0,1995-08-23
1507,946,8,D,amdrx@cunb.edu,1,1,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484,0,1994-12-15
1508,946,8,D,yn5ug@cunb.edu,1,2,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315,0,1994-09-18
1509,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19

## astype()

In [7]:
# reduce memory usage - spot categories
df.treatment.unique()
df.sex.unique()
df.nationality.unique()
df.grade.unique()
df["class"].unique()

array(['A', 'B', 'C', 'D'], dtype=object)

In [40]:
df_a = df.copy() # work on copy of df

# transform columns to category dtype
df_a[["grade", "class", "nationality", "sex", "treatment"]] = df_a[["grade", "class", "nationality", "sex", "treatment"]].astype("category")

df_a.info()

<class 'pandas.DataFrame'>
RangeIndex: 1510 entries, 0 to 1509
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   school_id          1510 non-null   int64
 1   grade              1510 non-null   category
 2   class              1510 non-null   category
 3   student_id         1510 non-null   str
 4   sex                1510 non-null   category
 5   nationality        1510 non-null   category
 6   grade_math_t1      1510 non-null   float64
 7   grade_language_t1  1510 non-null   float64
 8   grade_science_t1   1510 non-null   float64
 9   grade_math_t2      1508 non-null   float64
 10  grade_language_t2  1507 non-null   float64
 11  grade_science_t2   1508 non-null   float64
 12  treatment          1510 non-null   category
 13  date_of_birth      1510 non-null   str
dtypes: category(5), float64(6), int64(1), str(2)
memory usage: 113.8 KB

In [51]:
# memory reduction in KB
(df.memory_usage(deep=True).sum() - df_a.memory_usage(deep=True).sum())/1024

np.float64(113.279296875)

## clean date

### to_datetime

In [62]:
df_a["date_of_birth"] = pd.to_datetime(
    df_a["date_of_birth"],
    format="%Y-%m-%d",  # Adjust to your actual format
    errors="coerce",
)
df_a.info()

<class 'pandas.DataFrame'>
RangeIndex: 1510 entries, 0 to 1509
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   school_id          1510 non-null   int64
 1   grade              1510 non-null   category
 2   class              1510 non-null   category
 3   student_id         1510 non-null   str
 4   sex                1510 non-null   category
 5   nationality        1510 non-null   category
 6   grade_math_t1      1510 non-null   float64
 7   grade_language_t1  1510 non-null   float64
 8   grade_science_t1   1510 non-null   float64
 9   grade_math_t2      1508 non-null   float64
 10  grade_language_t2  1507 non-null   float64
 11  grade_science_t2   1508 non-null   float64
 12  treatment          1510 non-null   category
 13  date_of_birth      1505 non-null   datetime64[us]
dtypes: category(5), datetime64[us](1), float64(6), int64(1), str(1)
memory usage: 113.9 KB

In [65]:
df_a["date_of_birth"][:2]
df_a["date_of_birth"].isna().sum()
df_a[df_a["date_of_birth"].isna()]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
124,57,8,B,gtvmk@cunb.edu,1,1,7.954596,7.414694,7.036728,7.505426,6.965524,6.587558,0,NaT
548,262,8,A,yyhzg@cunb.edu,1,1,7.930281,7.403370,6.983867,8.950993,8.424081,8.004578,1,NaT
743,426,8,D,iya1k@cunb.edu,2,1,7.080474,5.793896,6.894132,6.068677,4.782099,5.882335,1,NaT
1005,499,8,A,otbkf@cunb.edu,1,1,4.333835,5.141400,5.548819,4.405107,5.212672,5.620091,1,NaT
1396,946,6,C,yofqa@cunb.edu,2,1,7.698935,7.704067,6.331823,7.373213,7.378346,6.006101,1,NaT

In [59]:
df_a[df_a.grade == 8]["date_of_birth"]

99      1995-06-28
100     1995-04-01
101     1995-05-24
102     1995-01-22
103     1994-09-25
           ...
1505    1995-07-04
1506    1995-08-23
1507    1994-12-15
1508    1994-09-18
1509    1994-12-19
Name: date_of_birth, Length: 533, dtype: str

## impute birthdate by grade

In [66]:
avg_birthdate_8_grade = df_a[df_a.grade == 8]["date_of_birth"].mean()
avg_birthdate_6_grade = df_a[df_a.grade == 6]["date_of_birth"].mean()
avg_birthdate_8_grade
avg_birthdate_6_grade

Timestamp('1997-02-24 04:35:17.647058')

## fillna()

In [67]:
df_a.loc[df_a.grade == 8, "date_of_birth"] = df_a.loc[
    df_a.grade == 8, "date_of_birth"
].fillna(avg_birthdate_8_grade)

In [68]:
df_a.loc[df_a.grade == 6, "date_of_birth"] = df_a.loc[
    df_a.grade == 6, "date_of_birth"
].fillna(avg_birthdate_6_grade)

In [69]:
# filled
df.loc[124] 
df.loc[1396]

school_id                       946
grade                             6
class                             C
student_id           yofqa@cunb.edu
sex                               2
nationality                       1
grade_math_t1              7.698935
grade_language_t1          7.704067
grade_science_t1           6.331823
grade_math_t2              7.373213
grade_language_t2          7.378346
grade_science_t2           6.006101
treatment                         1
date_of_birth            1997.03.09
Name: 1396, dtype: object

In [ ]:

df_a["year"] = df_a["date_of_birth"].dt.year
df_a["year"] = df_a["date_of_birth"].dt.year.astype("int32")
print(df_a["year"].dtype)

int32

## Missing Values

In [89]:
df_a.isna().sum()
df_a.isnull().sum()


# do nothing - assumption test not taken yet
df[df_a["language_t2"].isna()]
df[df_a["science_t2"].isna()]
df[df_a["math_t2"].isna()]

# df.dropna(subset=["language_t2", "science_t2", "math_t2"], inplace=True)

,school_id,grade,class,student_id,sex,nationality,math_t1,language_t1,science_t1,math_t2,language_t2,science_t2,treatment,date_of_birth
279,60,8,C,wa083@cunb.edu,2,2,5.218773,3.566172,3.838631,NaN,5.159542,5.432000,1,1994-11-25
848,458,8,A,whde3@cunb.edu,1,1,3.967109,2.758454,2.839566,NaN,2.664794,2.745906,0,1995-06-18

In [ ]:
# df_a.isnull().sum() # same
df_a[df_a.isnull().any(axis=1)]  # show all rows with null
df_a.isna().sum() / df_a.count()

school_id            0.000000
grade                0.000000
class                0.000000
student_id           0.000000
sex                  0.000000
nationality          0.000000
grade_math_t1        0.000000
grade_language_t1    0.000000
grade_science_t1     0.000000
grade_math_t2        0.001326
grade_language_t2    0.001991
grade_science_t2     0.001326
treatment            0.000000
date_of_birth        0.000000
year                 0.000000
dtype: float64

## Duplicates

In [ ]:
# show all duplicate rows
df_a[df_a.duplicated(keep=False)].sort_values(by=list(df_a.columns)) # sorts by all columns

df_a[df_a.duplicated(keep="last")] # show only last duplicate rows

,school_id,grade,class,student_id,sex,nationality,math_t1,language_t1,science_t1,math_t2,language_t2,science_t2,treatment,date_of_birth,year
39,57,6,C,hxddv@cunb.edu,1,1,8.478601,9.397897,9.220403,9.310329,10.000000,10.000000,1,1997-08-14,1997
150,57,6,C,hxddv@cunb.edu,1,1,8.478601,9.397897,9.220403,9.310329,10.000000,10.000000,1,1997-08-14,1997
377,141,7,C,xbpfw@cunb.edu,1,2,3.551834,3.614510,3.360211,6.036923,6.099598,5.845300,1,1996-08-23,1996
439,141,7,C,xbpfw@cunb.edu,1,2,3.551834,3.614510,3.360211,6.036923,6.099598,5.845300,1,1996-08-23,1996
484,262,6,D,icmoa@cunb.edu,2,1,6.352546,6.408562,7.955574,7.455129,7.511146,9.058157,0,1997-05-15,1997
595,262,6,D,icmoa@cunb.edu,2,1,6.352546,6.408562,7.955574,7.455129,7.511146,9.058157,0,1997-05-15,1997
509,262,7,B,kpoo9@cunb.edu,1,1,6.120440,5.928064,7.353246,3.811633,3.619257,5.044439,0,1995-09-14,1995
597,262,7,B,kpoo9@cunb.edu,1,1,6.120440,5.928064,7.353246,3.811633,3.619257,5.044439,0,1995-09-14,1995
551,262,8,B,q6c3l@cunb.edu,1,1,7.434781,7.259778,6.634327,9.370366,9.195363,8.569912,0,1995-06-20,1995
596,262,8,B,q6c3l@cunb.edu,1,1,7.434781,7.259778,6.634327,9.370366,9.195363,8.569912,0,1995-06-20,1995
690,426,7,D,jyj0s@cunb.edu,1,2,2.310155,2.757169,2.258084,3.836512,4.283526,3.784441,1,1995-12-19,1995
752,426,7,D,jyj0s@cunb.edu,1,2,2.310155,2.757169,2.258084,3.836512,4.283526,3.784441,1,1995-12-19,1995
739,426,8,C,9onh3@cunb.edu,1,1,5.514787,5.204074,5.131349,4.983463,4.672751,4.600025,1,1994-09-07,1994
753,426,8,C,9onh3@cunb.edu,1,1,5.514787,5.204074,5.131349,4.983463,4.672751,4.600025,1,1994-09-07,1994
792,458,6,D,xnthj@cunb.edu,1,2,5.552781,6.110878,6.384480,7.558939,8.117036,8.390638,1,1996-11-02,1996
892,458,6,D,xnthj@cunb.edu,1,2,5.552781,6.110878,6.384480,7.558939,8.117036,8.390638,1,1996-11-02,1996
1004,499,8,A,e9whz@cunb.edu,1,1,8.268938,7.926082,8.258870,9.584604,9.241748,9.574536,1,1995-01-06,1995
1053,499,8,A,e9whz@cunb.edu,1,1,8.268938,7.926082,8.258870,9.584604,9.241748,9.574536,1,1995-01-06,1995
1464,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19,1994
1509,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19,1994

In [ ]:
df_b = df_a.drop_duplicates("student_id")  # keeps first occurrence
df_b.duplicated().sum()

np.int64(0)

## reset_index()

In [115]:
# fill holes in the index and drop the old index
df_b.reset_index(drop=True, inplace=True)

## Placeholder values

In [103]:

# check for placeholder values
df_b.isin([99999.0]).sum()

df_b[df_b.isin([99999.0]).any(axis=1)]

df_b.describe().loc["max"]

school_id                      946.0
math_t1                         10.0
language_t1                     10.0
science_t1                      10.0
math_t2                      99999.0
language_t2                  99999.0
science_t2                   99999.0
date_of_birth    1997-08-30 00:00:00
year                          1997.0
Name: max, dtype: object

## replace()

In [104]:
import numpy as np

df_c = df_b.copy()
df_c.math_t2 = df_b.math_t2.replace(99999.0, np.nan)
df_c.language_t2 = df_b.language_t2.replace(99999.0, np.nan)
df_c.science_t2 = df_b.science_t2.replace(99999.0, np.nan)

In [105]:
df_c.describe().loc["max"]

school_id                      946.0
math_t1                         10.0
language_t1                     10.0
science_t1                      10.0
math_t2                         10.0
language_t2                     10.0
science_t2                      10.0
date_of_birth    1997-08-30 00:00:00
year                          1997.0
Name: max, dtype: object