# Boolean Indexing, Sorting

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://drive.google.com/uc?id=1oE-3rt17bFW7fOzDIjwFSEMPTIV3NvcO")

## Boolean Indexing

In [ ]:
df[df["school_id"] == 57] # filter rows by column value
df[df["school_id"] != 57] # filter rows by column value


df[df["school_id"].isin([57, 141])] # multiple values in a column
df[df["date_of_birth"]>"1995-01-01"] # greater than


df[df["grade_language_t1"].between(8.6, 8.7)] # between function


df[(df["grade_math_t1"] > 9) | (df["school_id"] == 57)] # or
df[(df["grade_math_t1"] > 9) & (df["school_id"] == 57)] # and


df[~(df["grade_math_t1"] < 8)] # negate - NOT less than 8
df[~df["school_id"].isin([57, 141])] # negate - NOT in list of values


# boolean indexing and choosing columns
df[df.grade_language_t1 > 9][["school_id", "grade"]]

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth
151,60,6,A,gjkjn@cunb.edu,1,1,6.895136,7.677860,6.568363,7.680624,8.463347,7.353851,1,1996-11-04
152,60,6,A,s23zr@cunb.edu,1,1,7.469003,8.627791,7.154632,6.778225,7.937013,6.463854,1,1996-09-07
153,60,6,A,xtycv@cunb.edu,1,2,4.402209,4.207442,5.461627,5.159038,4.964271,99999.000000,1,1996-10-09
154,60,6,A,atqc6@cunb.edu,1,2,4.471734,4.420371,4.888449,4.358915,4.307553,4.775631,1,1997-03-29
155,60,6,A,eojdp@cunb.edu,2,1,7.713092,6.951093,8.254861,7.346400,6.584401,7.888170,1,1997-04-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,946,8,D,jj36e@cunb.edu,1,1,4.938375,5.306647,4.985917,6.162418,6.530690,6.209960,0,1995-07-04
1506,946,8,D,ca1dg@cunb.edu,1,1,7.661931,8.360153,7.937165,8.179364,8.877586,8.454598,0,1995-08-23
1507,946,8,D,amdrx@cunb.edu,1,1,9.248758,8.534791,8.056641,8.773601,8.059634,7.581484,0,1994-12-15
1508,946,8,D,yn5ug@cunb.edu,1,2,5.689228,5.071503,5.338547,6.382995,5.765270,6.032315,0,1994-09-18
1509,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19

### query()

In [ ]:
df[df.grade_math_t1 > df.grade_math_t2]


df.query("grade_math_t1 > grade_math_t2")


# query can be cleaner for complex queries - keyword class needs backticks in query
df[(df.sex == 1) & (df["class"] == "C") & ((df.grade_math_t1 > 9.9) | (df.grade_math_t2 > 9.9))]
df.query("sex == 1 & `class` == 'C' & (grade_math_t1 > 9.9 | grade_math_t2 > 9.9)")

      grade_math_t1  grade_math_t2
0              2.05           1.18
1              7.86           7.55
2              7.12           6.18
5              7.04           6.27
6              8.61           7.64
...             ...            ...
1502           7.93           6.01
1503           6.55           4.89
1504           6.56           6.19
1507           9.25           8.77
1509           9.77           9.52

[606 rows x 2 columns]

In [ ]:
df.query("grade_math_t1 > grade_math_t2")[["grade_math_t1", "grade_math_t2"]].round(2)

### query in sql for comparison

In [ ]:
from pandasql import sqldf

# Define a helper function for SQL queries
def query(q):
    return sqldf(q, globals())

In [ ]:
result = query("""
    SELECT 
        ROUND(grade_math_t1) as grade_math_t1, 
        ROUND(grade_math_t2) as grade_math_t2,
    FROM df
    WHERE grade_math_t1 > grade_math_t2
""")

result

     grade_math_t1  grade_math_t2
0              2.0            1.0
1              8.0            8.0
2              7.0            6.0
3              7.0            6.0
4              9.0            8.0
..             ...            ...
601            8.0            6.0
602            7.0            5.0
603            7.0            6.0
604            9.0            9.0
605           10.0           10.0

[606 rows x 2 columns]

## Sorting

In [17]:
df.sort_values(by="school_id", ascending=True) # sort by column
df.sort_values(by=["school_id", "grade_language_t1"], ascending=[True, False]) # sort by multiple columns

df.sort_index() # sort by index
df.sort_index(ascending=False) # sort by index in descending order

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth,rank
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.000000,10.000000,9.194739,1,1997-03-25,1.0
1464,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19,1.0
451,262,6,A,swejn@cunb.edu,1,1,10.000000,10.000000,9.368304,10.000000,10.000000,9.377335,1,1997-03-26,1.0
1082,812,6,C,nye4a@cunb.edu,1,1,9.561568,10.000000,10.000000,10.000000,10.000000,10.000000,1,1997-03-09,1.0
1190,812,8,C,gdt3t@cunb.edu,1,1,8.528551,10.000000,9.781599,7.673200,9.144649,8.926248,0,1994-11-13,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,458,6,C,y8d1g@cunb.edu,1,2,0.000000,1.332429,0.000000,0.000000,0.000000,0.000000,0,1997-03-12,1486.0
1261,881,7,A,pm1p8@cunb.edu,1,1,1.247593,1.262528,2.709209,0.415647,0.430582,1.877262,0,1995-09-11,1487.0
965,499,7,C,lqmmt@cunb.edu,1,1,1.630344,1.212652,2.531448,2.886153,2.468461,3.787257,1,1996-06-29,1488.0
656,426,7,A,f6btr@cunb.edu,1,2,1.565799,1.084899,1.630079,1.329981,0.849082,1.394261,0,1996-05-15,1489.0
303,141,6,B,ydca8@cunb.edu,1,1,2.679972,0.993821,0.920921,0.991779,0.000000,0.000000,0,1996-11-02,1490.0

### nlargest, nsmallest, rank

In [14]:
df.nlargest(5, "grade_language_t1") # top 5 rows with largest values in column
df.nsmallest(5, "grade_language_t1") # top 5 rows with smallest values in column


# add a new column with rank based on another column
df["rank"] = df["grade_language_t1"].rank(ascending=False, method='dense') 

df.sort_values(by="rank")

,school_id,grade,class,student_id,sex,nationality,grade_math_t1,grade_language_t1,grade_science_t1,grade_math_t2,grade_language_t2,grade_science_t2,treatment,date_of_birth,rank
31,57,6,C,0eiwm@cunb.edu,1,1,9.737252,10.000000,8.927517,10.000000,10.000000,9.194739,1,1997-03-25,1.0
1464,946,8,A,eohgp@cunb.edu,1,1,9.768719,10.000000,8.493072,9.515601,9.746882,8.239953,0,1994-12-19,1.0
451,262,6,A,swejn@cunb.edu,1,1,10.000000,10.000000,9.368304,10.000000,10.000000,9.377335,1,1997-03-26,1.0
1082,812,6,C,nye4a@cunb.edu,1,1,9.561568,10.000000,10.000000,10.000000,10.000000,10.000000,1,1997-03-09,1.0
1190,812,8,C,gdt3t@cunb.edu,1,1,8.528551,10.000000,9.781599,7.673200,9.144649,8.926248,0,1994-11-13,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,458,6,C,y8d1g@cunb.edu,1,2,0.000000,1.332429,0.000000,0.000000,0.000000,0.000000,0,1997-03-12,1486.0
1261,881,7,A,pm1p8@cunb.edu,1,1,1.247593,1.262528,2.709209,0.415647,0.430582,1.877262,0,1995-09-11,1487.0
965,499,7,C,lqmmt@cunb.edu,1,1,1.630344,1.212652,2.531448,2.886153,2.468461,3.787257,1,1996-06-29,1488.0
656,426,7,A,f6btr@cunb.edu,1,2,1.565799,1.084899,1.630079,1.329981,0.849082,1.394261,0,1996-05-15,1489.0
303,141,6,B,ydca8@cunb.edu,1,1,2.679972,0.993821,0.920921,0.991779,0.000000,0.000000,0,1996-11-02,1490.0

### value_counts() 
for categorical columns

In [30]:
df.value_counts("school_id") # count unique values in a column

school_id
499    161
262    158
426    156
812    153
881    153
57     151
946    150
141    146
60     143
458    139
Name: count, dtype: int64